#version 430 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
uniform layout(binding = 0, rgba32f) writeonly image2D screen;

void main() {
    ivec2 coordinate = ivec2(gl_GlobalInvocationID.xy);
    vec3 color = vec3(0.0, 0.0, 0.0);
    color.r = coordinate.x / float(gl_NumWorkGroups.x);
    color.g = coordinate.y / float(gl_NumWorkGroups.y);
    imageStore(screen, coordinate, vec4(color, 1.0));
}
